config/routes.rb
Redit::Application.routes.draw do
  
  resources :users

  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"
  root "welcome#index"


end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  helper_method :current_user, :logged_in?
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && ( user.authenticate(params[:password]) )
      
      # save the user_id in the session hash
      session[:user_id] = user.id

      # and redirect to that user's home page
      redirect_to( root_path )
    else

      # the email/password is wrong!
      @message = "This email and password combination does not exist."
      redirect_to ( root_path )
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new

    render(:new)
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render(:new)
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email)
  end

  def authenticate
    unless logged_in?
      redirect_to root_path
    end
  end

  def authorize
    unless current_user == @user
      redirect_to root_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="nav-bar">
    <% if logged_in? %>
        <ul>
          <li>
            <%= link_to "Heyo #{current_user.username}" %>
          </li>
          <li>
            <%= link_to "Logout", session_path, method: :delete %>
          </li>
        </ul>
    <% else %>
      <ul>
        <li><%= link_to "Join!", new_user_path %></li>
        <li>
          <%= form_tag session_path do %>
            <%= label_tag :username %>
            <%= text_field_tag :username %>
            <%= label_tag :password %>
            <%= password_field_tag :password %>
            <%= submit_tag "Login" %>
          <% end %>
        </li>
      </ul>
    <% end %>
  </nav>

  <% unless @message.nil? %>
    <div id="errors">
      <h3>Errors!</h3>
      <ul>
        <li><em><%= @message %></em></li>
      </ul>
    </div>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "join-form"} do |f| %>

  <div class="label-input">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="label-input">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="label-input">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="label-input">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit @user.id.nil? ? "Join!" : "Save Changes" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<% unless @user.errors.messages.empty? %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <% @user.errors.messages.each do |field,error| %>
        <li><em><%= "#{field.capitalize.to_s.gsub("_", " ")} #{error.first}!" %></em></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render "form" %>

app/views/welcome/index.html.erb
<h1>Hallo</h1>